export const chats = [
  {
    id: 1,
    name: "Jacquenetta Slowgrave",
    message: "Great! Looking forward to it. Se...",
    time: "10 minutes",
    unreadCount: 8,
    avatar: "JS",
    isOnline: true,
    isActive: true,
  },
  {
    id: 2,
    name: "Nickola Peever",
    message: "Sounds perfect! I've been wanti...",
    time: "40 minutes",
    unreadCount: 2,
    avatar: "NP",
    isOnline: true,
    isActive: false,
  },
  {
    id: 3,
    name: "Farand Hume",
    message: "How about 7 PM at the new Italian ...",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "FH",
    isOnline: true,
    isActive: false,
  },
  {
    id: 4,
    name: "Ossie Peasey",
    message: "Hey Bonnie, yes, definitely! What ti...",
    time: "13 days",
    unreadCount: 0,
    avatar: "OP",
    isOnline: false,
    isActive: false,
  },
  {
    id: 5,
    name: "Hall Negri",
    message: "Thanks for the update!",
    time: "2 days",
    unreadCount: 0,
    avatar: "HN",
    isOnline: false,
    isActive: false,
  },
  // Add more chats to test scrolling
  {
    id: 6,
    name: "Alex Johnson",
    message: "Can we reschedule the meeting?",
    time: "3 days",
    unreadCount: 1,
    avatar: "AJ",
    isOnline: true,
    isActive: false,
  },
  {
    id: 7,
    name: "Sarah Wilson",
    message: "The project looks great so far",
    time: "5 days",
    unreadCount: 0,
    avatar: "SW",
    isOnline: false,
    isActive: false,
  },
  {
    id: 8,
    name: "Mike Davis",
    message: "Let me know when you're available",
    time: "1 week",
    unreadCount: 3,
    avatar: "MD",
    isOnline: true,
    isActive: false,
  },
];
